
#! /usr/bin/env python3

# List of states
states = [
    'Florida', 'Pennsylvania', 'Ohio', 'Michigan', 'New Jersey', 'Missouri', 
    'Wisconsin', 'Minnesota', 'Colorado', 'Iowa', 'Oregon', 'Arkansas', 
    'New Mexico', 'Nevada', 'New Hampshire', 'Maine', 'West Virginia', 
    'Hawaii', 'Alabama', 'Alaska', 'Arizona', 'California', 'Connecticut', 
    'Delaware', 'District of Columbia', 'Georgia', 'Idaho', 'Illinois', 
    'Indiana', 'Kansas', 'Kentucky', 'Louisiana', 'Maryland', 'Massachusetts', 
    'Mississippi', 'Montana', 'Nebraska', 'New York', 'North Carolina', 
    'North Dakota', 'Oklahoma', 'Rhode Island', 'South Carolina', 'South Dakota', 
    'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'Wyoming'
]

# Dictionary of votes per state
votes = {
    'Alabama': 9,
    'Alaska': 3,
    'Arizona': 10,
    'Arkansas': 6,
    'California': 55,
    'Colorado': 9,
    'Connecticut': 7,
    'Delaware': 3,
    'District of Columbia': 3,
    'Florida': 27,
    'Georgia': 15,
    'Hawaii': 4,
    'Idaho': 4,
    'Illinois': 21,
    'Indiana': 11,
    'Iowa': 7,
    'Kansas': 6,
    'Kentucky': 8,
    'Louisiana': 9,
    'Maine': 4,
    'Maryland': 10,
    'Massachusetts': 12,
    'Michigan': 17,
    'Minnesota': 10,
    'Mississippi': 6,
    'Missouri': 11,
    'Montana': 3,
    'Nebraska': 5,
    'Nevada': 5,
    'New Hampshire': 4,
    'New Jersey': 15,
    'New Mexico': 5,
    'New York': 31,
    'North Carolina': 15,
    'North Dakota': 3,
    'Ohio': 20,
    'Oklahoma': 7,
    'Oregon': 7,
    'Pennsylvania': 21,
    'Rhode Island': 4,
    'South Carolina': 8,
    'South Dakota': 3,
    'Tennessee': 11,
    'Texas': 34,
    'Utah': 5,
    'Vermont': 3,
    'Virginia': 13,
    'Washington': 11,
    'West Virginia': 5,
    'Wisconsin': 10,
    'Wyoming': 3
}

# Dictionary of state codes
stcode = {
    'Alabama': 'al',
    'Alaska': 'ak',
    'Arizona': 'az',
    'Arkansas': 'ar',
    'California': 'ca',
    'Colorado': 'co',
    'Connecticut': 'ct',
    'Delaware': 'de',
    'District of Columbia': 'dc',
    'Florida': 'fl',
    'Georgia': 'ga',
    'Hawaii': 'hi',
    'Idaho': 'id',
    'Illinois': 'il',
    'Indiana': 'in',
    'Iowa': 'ia',
    'Kansas': 'ks',
    'Kentucky': 'ky',
    'Louisiana': 'la',
    'Maine': 'me',
    'Maryland': 'md',
    'Massachusetts': 'ma',
    'Michigan': 'mi',
    'Minnesota': 'mn',
    'Mississippi': 'ms',
    'Missouri': 'mo',
    'Montana': 'mt',
    'Nebraska': 'ne',
    'Nevada': 'nv',
    'New Hampshire': 'nh',
    'New Jersey': 'nj',
    'New Mexico': 'nm',
    'New York': 'ny',
    'North Carolina': 'nc',
    'North Dakota': 'nd',
    'Ohio': 'oh',
    'Oklahoma': 'ok',
    'Oregon': 'or',
    'Pennsylvania': 'pa',
    'Rhode Island': 'ri',
    'South Carolina': 'sc',
    'South Dakota': 'sd',
    'Tennessee': 'tn',
    'Texas': 'tx',
    'Utah': 'ut',
    'Vermont': 'vt',
    'Virginia': 'va',
    'Washington': 'wa',
    'West Virginia': 'wv',
    'Wisconsin': 'wi',
    'Wyoming': 'wy'
}