
#! /usr/bin/env python3

# List of states
states = [
    'Florida', 'Pennsylvania', 'Ohio', 'Michigan', 'New Jersey', 'Missouri', 
    'Wisconsin', 'Minnesota', 'Colorado', 'Iowa', 'Oregon', 'Arkansas', 
    'New Mexico', 'Nevada', 'New Hampshire', 'Maine', 'West Virginia', 
    'Hawaii', 'Alabama', 'Alaska', 'Arizona', 'California', 'Connecticut', 
    'Delaware', 'District of Columbia', 'Georgia', 'Idaho', 'Illinois', 
    'Indiana', 'Kansas', 'Kentucky', 'Louisiana', 'Maryland', 'Massachusetts', 
    'Mississippi', 'Montana', 'Nebraska', 'New York', 'North Carolina', 
    'North Dakota', 'Oklahoma', 'Rhode Island', 'South Carolina', 'South Dakota', 
    'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'Wyoming'
]

votes = {
    'Alabama': 9,
    'Alaska': 3,
    'Arizona': 11,
    'Arkansas': 6,
    'California': 54,
    'Colorado': 10,
    'Connecticut': 7,
    'Delaware': 3,
    'District of Columbia': 3,
    'Florida': 30,
    'Georgia': 16,
    'Hawaii': 4,
    'Idaho': 4,
    'Illinois': 19,
    'Indiana': 11,
    'Iowa': 6,
    'Kansas': 6,
    'Kentucky': 8,
    'Louisiana': 8,
    'Maine': 4,
    'Maryland': 10,
    'Massachusetts': 11,
    'Michigan': 15,
    'Minnesota': 10,
    'Mississippi': 6,
    'Missouri': 10,
    'Montana': 4,
    'Nebraska': 5,
    'Nevada': 6,
    'New Hampshire': 4,
    'New Jersey': 14,
    'New Mexico': 5,
    'New York': 28,
    'North Carolina': 16,
    'North Dakota': 3,
    'Ohio': 17,
    'Oklahoma': 7,
    'Oregon': 8,
    'Pennsylvania': 19,
    'Rhode Island': 4,
    'South Carolina': 9,
    'South Dakota': 3,
    'Tennessee': 11,
    'Texas': 40,
    'Utah': 6,
    'Vermont': 3,
    'Virginia': 13,
    'Washington': 12,
    'West Virginia': 4,
    'Wisconsin': 10,
    'Wyoming':3
}

# Dictionary of state codes
stcode = {
    'Alabama': 'al',
    'Alaska': 'ak',
    'Arizona': 'az',
    'Arkansas': 'ar',
    'California': 'ca',
    'Colorado': 'co',
    'Connecticut': 'ct',
    'Delaware': 'de',
    'District of Columbia': 'dc',
    'Florida': 'fl',
    'Georgia': 'ga',
    'Hawaii': 'hi',
    'Idaho': 'id',
    'Illinois': 'il',
    'Indiana': 'in',
    'Iowa': 'ia',
    'Kansas': 'ks',
    'Kentucky': 'ky',
    'Louisiana': 'la',
    'Maine': 'me',
    'Maryland': 'md',
    'Massachusetts': 'ma',
    'Michigan': 'mi',
    'Minnesota': 'mn',
    'Mississippi': 'ms',
    'Missouri': 'mo',
    'Montana': 'mt',
    'Nebraska': 'ne',
    'Nevada': 'nv',
    'New Hampshire': 'nh',
    'New Jersey': 'nj',
    'New Mexico': 'nm',
    'New York': 'ny',
    'North Carolina': 'nc',
    'North Dakota': 'nd',
    'Ohio': 'oh',
    'Oklahoma': 'ok',
    'Oregon': 'or',
    'Pennsylvania': 'pa',
    'Rhode Island': 'ri',
    'South Carolina': 'sc',
    'South Dakota': 'sd',
    'Tennessee': 'tn',
    'Texas': 'tx',
    'Utah': 'ut',
    'Vermont': 'vt',
    'Virginia': 'va',
    'Washington': 'wa',
    'West Virginia': 'wv',
    'Wisconsin': 'wi',
    'Wyoming': 'wy'
}

nsurls = {
    'Arizona': 'https://static.dwcdn.net/data/2TpYN.csv',
    'Florida': 'https://static.dwcdn.net/data/q6COK.csv',
    'Georgia': 'https://static.dwcdn.net/data/N2snp.csv',
    'Michigan': 'https://static.dwcdn.net/data/CHPeH.csv',
    'Minnesota': 'https://static.dwcdn.net/data/zrzJX.csv',
    'Nevata': 'https://static.dwcdn.net/data/hXyNT.csv',
    'New Hampshire': 'https://static.dwcdn.net/data/et7Vl.csv',
    'North Carolina': 'https://static.dwcdn.net/data/NRcBO.csv',
    'Pennsylvania': 'https://static.dwcdn.net/data/aFbPu.csv',
    'Texas': 'https://static.dwcdn.net/data/6dAPy.csv',
    'Virginia': 'https://static.dwcdn.net/data/eofsh.csv',
    'Wisconsin': 'https://static.dwcdn.net/data/UFzgk.csv'
}
