name: simulate 

on: 
  workflow_dispatch
  #schedule:
  #  - cron: '0 0 * * 1' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r _code/requirements.txt

      - name: execute py script # run main.py
        run: python _code/simulate.py

      - name: Commit files
        uses: actions/upload-artifact@v4
        with:
            path: assets/harrisvotes.png
      #   id: commit
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "github-actions"
      #     git add --all
      #     if [-z "$(git status --porcelain)"]; then
      #        echo "::set-output name=push::false"
      #     else
      #        git commit -m "Add changes" -a
      #        echo "::set-output name=push::true"
      #     fi
      #   shell: bash
      # - name: Push changes
      #   if: steps.commit.outputs.push == 'true'
      #   uses: ad-m/github-push-action@master
      #   with:
      #      github_token: ${{ secrets.GITHUB_TOKEN }}
