name: simulate 

on: 
  workflow_dispatch
  # schedule:
  #  - cron: '0 3 * * *' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content
        with:
          ref: main

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r _code/requirements.txt

      - name: execute py script # run main.py
        run: python _code/simulate.py

      - name: create commit message
        id: commit_message_step
        run: date >> $GITHUB_OUTPUT
        
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        id: commit
        with:
          commit_message: ${{ steps.commit_message_step.outputs.commit_message }}
